In [94]:
import numpy as np

## Q#1: Create x array with elements equal to 1.

In [95]:
# write your code here ^_^
x =np.ones([3,3])
x

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

## Q#2: Create y array with elements equal to 0.

In [96]:
# write your code here ^_^
y = np.zeros([3,3])
y

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

## Q#3: Add x and y arrays.

In [97]:
# write your code here ^_^
np.add(x,y)

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

## Q#4: Print x array characteristics (e.g: dimension, shape, size, type).

In [98]:
# write your code here ^_^
print('''
X shape is {}
X size is {}
X dimension is {}
'''.format(x.shape,x.size,x.ndim))


X shape is (3, 3)
X size is 9
X dimension is 2



## Q#5: Create a 2D array "called w" as the following:

|       |          |
| ----- | -------- |
| 11    | 12       |
| 13    | 14       |
| 15    | 16       |


In [99]:
# write your code here ^_^
w = np.array([[11,12],[13,14],[15,16]])
w

array([[11, 12],
       [13, 14],
       [15, 16]])

## Q#6: Create z array contains the numbers from 1 to 3.

In [100]:
# write your code here ^_^
z=np.arange(1,4)
z

array([1, 2, 3])

## Q#7: Combine the arrays z and w in horizontal way then save it in a new variable "newArray".

In [101]:
# write your code here ^_^
newArray = np.hstack((z.reshape(-1, 1), w))
newArray

array([[ 1, 11, 12],
       [ 2, 13, 14],
       [ 3, 15, 16]])

## Q#8: Print all elements of "newArray" using the loop.

In [102]:
# write your code here ^_^
for r in newArray:
    for num in r:
        print(num)


1
11
12
2
13
14
3
15
16


## Q#9: Reverse the columns and rows of "newArray".

In [103]:
# write your code here ^_^
fliped_array = np.transpose(newArray)
fliped_array

array([[ 1,  2,  3],
       [11, 13, 15],
       [12, 14, 16]])

In [104]:
fliped_array = np.flip(newArray)
fliped_array


array([[16, 15,  3],
       [14, 13,  2],
       [12, 11,  1]])

## Q#10: Decrement all elements of "newArray" with 1.

In [105]:
# write your code here ^_^
newArray -=1
newArray

array([[ 0, 10, 11],
       [ 1, 12, 13],
       [ 2, 14, 15]])

## Q#11: Find smallest and biggest values in "newArray".

In [106]:
# write your code here ^_^
print ('''
the smallest value is {}
the beggest value is {}
'''.format(newArray.min(),newArray.max()))


the smallest value is 0
the beggest value is 15



## Q#12: Print the first row of "newArray" using indexing.

In [107]:
# write your code here ^_^
newArray[0,0:]

array([ 0, 10, 11])

## Q#13: Print the number equals 12 of "newArray" using indexing.

In [108]:
# write your code here ^_^
newArray[1,1]

12

## Q#14: Print the numbers equal 0 and 13 of "newArray" using indexing.

In [109]:
# write your code here ^_^
print(newArray[0,0])
newArray[1,2]

0


13

## Q#15: Change the shape of "newArray" to (9,1).

In [110]:
# write your code here ^_^
newArray.reshape(9, 1)


array([[ 0],
       [10],
       [11],
       [ 1],
       [12],
       [13],
       [ 2],
       [14],
       [15]])

## Q#16: Change the shape of "newArray" to (3,2).

In [111]:
# write your code here ^_^
newArray.reshape(3,2)


ValueError: cannot reshape array of size 9 into shape (3,2)

# Well Done 🎉